export const recommendationScoringConfig = {
  academicGpaBands: [
    { maxGpa: 5, minGpa: 4.5, score: 85 },
    { maxGpa: 4.5, minGpa: 4, score: 75 },
    { maxGpa: 4, minGpa: 3.5, score: 65 },
    { maxGpa: 3.5, minGpa: 3, score: 50 },
    { maxGpa: 3, minGpa: 0, score: 35 },
  ],
  academicRankBands: [
    { maxPercentile: 3, score: 100 },
    { maxPercentile: 5, score: 92 },
    { maxPercentile: 10, score: 82 },
    { maxPercentile: 15, score: 72 },
    { maxPercentile: 20, score: 62 },
    { maxPercentile: 30, score: 48 },
    { maxPercentile: 100, score: 30 },
  ],
  cet4Bands: [
    { minScore: 550, score: 85 },
    { minScore: 520, score: 75 },
    { minScore: 500, score: 68 },
    { minScore: 425, score: 55 },
    { minScore: 0, score: 25 },
  ],
  cet6Bands: [
    { minScore: 550, score: 100 },
    { minScore: 520, score: 90 },
    { minScore: 500, score: 82 },
    { minScore: 425, score: 68 },
    { minScore: 0, score: 30 },
  ],
  competitionAwardBonus: 5,
  competitionLevelScores: {
    INTERNATIONAL: 95,
    NATIONAL: 82,
    PROVINCIAL: 62,
    UNIVERSITY: 38,
  },
  confidence: {
    base: 35,
    competition: 10,
    english: 15,
    experience: 10,
    gpaOnlyAcademic: 15,
    ranking: 25,
    research: 5,
  },
  experience: {
    internshipRelevance: { HIGH: 45, LOW: 15, MEDIUM: 30 },
    paperAuthorshipBonus: { CO_FIRST: 15, FIRST: 20, OTHER: 5 },
    paperStatus: { ACCEPTED: 65, DRAFT: 20, PUBLISHED: 80, SUBMITTED: 40 },
    researchOutputBonus: 10,
  },
  research: {
    countBonus: 8,
    duration: { long: 20, medium: 12, short: 5 },
    output: 25,
    role: { CORE: 30, LEAD: 40, PARTICIPANT: 18, UNKNOWN: 10 },
  },
  version: "recommendation-v0.1",
  weights: {
    academics: 40,
    competition: 15,
    english: 15,
    experience: 10,
    research: 20,
  },
} as const;
